### ISSUE TITLE
[Question] How to pass parameters to the module?

### ISSUE THREAD

**Issue by memfis19** [rakshakhegde/DaggerAndroidInjector#2]
How to pass parameters to the module? It's not clear. Can you please show an example?
For example `MainModule` should receive some params in constructor.

**Comment by rakshakhegde** [comment]
With this way you cannot really instantiate a Module. You have to use `@Provides` from the `AppModule` or anything convenient.

**Comment by memfis19** [comment]
Ok. Thank you.
